### ISSUE TITLE
[FEAT] Simulator 적용

### ISSUE THREAD

**Issue by seongmin221** [seongmin221/Eyebrow-Simulator#12]
## ⭐️ 구현 배경

Simulator 적용하기 위한 이슈

## ☑️ TODO

- [x] 눈썹 asset 추가
- [x] 눈썹 리스트 볼 수 있는 collectionView UI
- [x] 눈썹 선택 시 특정 위치에 눈썹 생성
- [x] 선택한 눈썹 별로 눈썹 모양 변경
