### ISSUE TITLE
[FEAT] 촬영한 이미지 볼 수 있게 하기

### ISSUE THREAD

**Issue by seongmin221** [seongmin221/Eyebrow-Simulator#5]
## ⭐️ 구현 배경
촬영한 이미지를 볼 수 있게 하려고 합니닷 -> navigation 으로 할지, bottomsheet 로 할지 ... 고민

## ☑️ TODO

- [x] 촬영 이미지 확인할 수 있는 뷰 생성
- [x] Coordinator Pattern 공부
- [x] Coordinator Pattern 적용
- [ ] PreviewLayer 에 실루엣 보더 추가
